---

mongodb_service: "mongod"
mongodb_port: 27017
mongodb_bind_ip: "0.0.0.0"

mongodb_versions:
  Debian: "6.0"
  RedHat: "4.4"

mongodb_version: "{{ mongodb_versions[ansible_facts['os_family']] }}"
