---
# =========================
# MongoDB Version
# =========================
mongodb_version: "6.0"

# =========================
# Package
# =========================
mongodb_package: "mongodb-org"

# =========================
# Service Name
# =========================
mongodb_service: "mongod"

# =========================
# Network Configuration
# =========================
mongodb_port: 27017
mongodb_bind_ip: "0.0.0.0"
