plugin: amazon.aws.aws_ec2

regions:
  - ap-south-1

filters:
  tag:Name: mongo-instance-*

keyed_groups:
  - key: tags.Name
    prefix: Name

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
  ansible_user: ubuntu
  ansible_ssh_private_key_file: /home/ubuntu/.ssh/mumbai.pem
