plugin: amazon.aws.aws_ec2

regions:
  - ap-south-1

filters:
  tag:Name: mongo-instance-*

keyed_groups:
  - key: tags.Name
    prefix: tag_Name

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
  ansible_user: ubuntu
  ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/mumbai.pem
  ansible_python_interpreter: /usr/bin/python3
